### ISSUE TITLE
Add Tau-U variations

### ISSUE THREAD

**Issue by jepusto** [jepusto/SingleCaseES#1]
Add options for different definitions of Tau-U.

**Comment by MattiasErhardsson** [comment]
Hi! I was recently spurred to learn R in part to employ Tau-U in my research. On the subject of Tau-U variations, which variant does this package use? I am unable to discern this from the documentation.

**Comment by DMSwan** [comment]
The mathematical descriptions of all effect sizes calculated by the SingleCaseES package can be found in this vignette: https://cran.r-project.org/web/packages/SingleCaseES/vignettes/Effect-size-definitions.html

**Comment by MattiasErhardsson** [comment]
Am I correct to assume that the package uses _Tau-UA vs. B − trend A_, and not _Tau-UA vs. B + trend B − trend A_?

**Comment by DMSwan** [comment]
Yes, that looks correct to me. James is at a conference and unplugged from his e-mail at the moment but I imagine he will see this and confirm some time next week.

**Comment by MattiasErhardsson** [comment]
Ok, thanks for the expedient answer!

**Comment by jepusto** [comment]
Yes, the package only implements Tau-UA vs. B − trend A, using the same formula as implemented at singlecaseresearch.org. I have never seen the other variants of Tau-U implemented in practice and so programming them into this package is very low priority.
