### ISSUE TITLE
Add outcome measurement details for example datasets.

### ISSUE THREAD

**Issue by jepusto** [jepusto/SingleCaseES#15]
In help file for Thorne data, add details about how each of the outcomes were collected. Include measurement procedure, observation session length, number and length of intervals (for academic engagement, if applicable).

**Comment by jepusto** [comment]
In help file for Schmidt and Stichter data, add details about how each of the outcomes were collected. Include measurement procedure, observation session length, number and length of intervals.

**Comment by DMSwan** [comment]
Updated in commit 8fc6e658a303099a43496bebb31d844da6c978af

**Comment by DMSwan** [comment]
Okay technically completed in a6d09b268d5dcb32f384e67ec870b7d504a141f3

**Comment by jepusto** [comment]
Super. Is there anything else that you think we should handle before
submitting to CRAN?

**Comment by DMSwan** [comment]
Do you think I should do the vignette first or are we at "good enough"?

**Comment by jepusto** [comment]
Would you have time to put together a vignette this week (say by next
Monday)? If so, I'm okay holding off on CRAN submission until then.

**Comment by DMSwan** [comment]
Yeah, I'll do it on Thursday.
