### ISSUE TITLE
Add unit tests for SCD_effect_sizes()

### ISSUE THREAD

**Issue by jepusto** [jepusto/SingleCaseES#34]
Add unit tests for SCD_effect_sizes() using the shinytest package. Ideally, these would re-run the built in-examples (using all available effect sizes) and check whether the results are consistent with a direct call to batch_calc_ES().

**Comment by DMSwan** [comment]
I was just wondering if there was a convenient way to test shiny packages.

**Comment by jepusto** [comment]
Added with commit c62d53cd577083db5ef60343b6142f2541b80d45.
