### ISSUE TITLE
Revise batch calculations

### ISSUE THREAD

**Issue by jepusto** [jepusto/SingleCaseES#36]
Revise batch calculations in batch_calc_ES() and the gem shiny app to use pure dplyr (maybe with the new group_map?). Remove the dependency on purrrlyr.

**Comment by DMSwan** [comment]
I poked at this a little bit, and at the moment it seems like inside of a group_map, you can't refer to a vector of the subset dataframe supplied to the function (.dat in do() and .x in group_map) using the [[ ]] notation to get nice vectors out of it, so the simple solution of changing the do() to a group_map and the .dat to .x doesn't appear to work. This may require a fairly tedious rebuild of the batch_calculator function.

**Comment by jepusto** [comment]
The new version (dplyr v1.0.0) of `summerise()` should help with this!

**Comment by jepusto** [comment]
Right now setting format = "wide" seems to really slow down the calculations. It's not clear to me why that should be.

**Comment by jepusto** [comment]
Resolved with commit 23bae00d53e0a00f604c374c3321ed0de2d99851
