### ISSUE TITLE
Add log ratio of medians effect size measure

### ISSUE THREAD

**Issue by jepusto** [jepusto/SingleCaseES#38]
Add log ratio of medians to available ES measures in functions and shiny app. See the following reference for formulas:
> Bonett, D. G., & Price, R. M. (2019). Interval estimation for linear functions of medians in within-subject and mixed designs. British Journal of Mathematical and Statistical Psychology, in press. doi:10.1111/bmsp.12171

**Comment by manchen07** [comment]
Bonett, D. G. & Price Jr, R. M. (2020). Confidence Intervals for Ratios of Means and Medians. _Journal of Educational and Behavioral Statistics, 45_(6), 750-770. doi:10.3102/1076998620934125
