### ISSUE TITLE
Fix close-out in GEM app

### ISSUE THREAD

**Issue by jepusto** [jepusto/SingleCaseES#39]
Stop the `shine_gem_scd()` app when the UI is closed.

**Comment by DMSwan** [comment]
Sorry - after I put the close code in the wrong server, I meant to put the new fix in a different branch then offer a pull request. But then I got distracted trying and failing to fix a bigger problem that I messed up and pushed to the Master branch!! I won't do it again. It's a small fix so hopefully everything is OK.
