### ISSUE TITLE
Plug in updated LRRd and LRRi to Shiny app.

### ISSUE THREAD

**Issue by jepusto** [jepusto/SingleCaseES#5]
LRRd and LRRi functions are now available. Add to the Shiny app and plug in arguments to feature selection boxes.

**Comment by jepusto** [comment]
Also LOR.

**Comment by jepusto** [comment]
The additional options in the single-entry calculator also need to get plugged in for the batch calculator.

**Comment by DMSwan** [comment]
Okay close for real this time.
