### ISSUE TITLE
Schmidt2007 data

### ISSUE THREAD

**Issue by ASKurz** [jepusto/SingleCaseES#66]
Hi @jepusto, a comment and question on the `Schmidt2007` data. 

* When I look at Table 1 in the original thesis document ([here](https://kuscholarworks.ku.edu/bitstream/handle/1808/32097/Schmidt_Anna_C_2007_5349292.pdf?sequence=1&isAllowed=y)), it appears that the names in the thesis are different from the names in the data set. E.g., Lilly's data in Table 1 of the thesis appears to be labeled as belonging to Faith in the `Schmidt2007` data.
* In both your documentation (i.e., the `Metric` column) and in the thesis, it appears that the *Disruptive Behaviors* were count variables. But when I look at the values in your `Outcome` column, I see values with decimal places. How can counts have fractional values?

Thanks for the great package,
Solomon

**Comment by jepusto** [comment]
Hi Solomon,

Thanks very much for pointing this out, and I'm sorry for the extended delay in responding. 
* I agree with your assessment that the case pseudonyms in our `Schmidt2007` dataset appear to be mis-labeled. We will work on correcting this.
* We created this dataset by extracting datapoints from the published graph, which introduces a small degree of measurement error. Given the resolution of the graph, it was not possible to identify points down to the exact integer value. It seems to me that, for the disruptive behavior outcome, the values could safely be rounded to the nearest integer.

Kind Regards,
James

**Comment by ASKurz** [comment]
Good deal.
