### ISSUE TITLE
Option to return baseline standard deviation for within-case SMD

### ISSUE THREAD

**Issue by rbcavanaugh** [jepusto/SingleCaseES#67]
Thanks for all your work on this package. Would you consider including an option to return the baseline SD for the within-case SMD in the calc_SMD() function? 

In the rare event that I want to calculate the within-case SMD, I like to evaluate the baseline SD so it would be nice to have it returned by the function. I'm happy to do this on my own, but I thought I would make the suggestion here. Something like:

```
calc_SMD <- function(A_data, B_data, 
                     improvement = "increase",
                     std_dev = "baseline", 
                     bias_correct = TRUE, 
                     confidence = .95, warn = TRUE, bl_var = FALSE, ...) {
```

and at the end of the function:

```
if(bl_var){
     res$baseline_SD = sqrt(s_sq) 
}
```

Editing to add: Adding this information might also help users interpret cases in the batch SMD where baseline SD = 0 if you wanted to return NA and a warning instead of an error in #43.

**Comment by jepusto** [comment]
Yes, we can add this. The function includes the option `std_dev` for controlling whether the SMD is calculated using the baseline SD or the pooled SD (across baseline and treatment). Do you think it would make sense for the function to report the pooled SD if `std_dev = "pool"` and the baseline SD if `std_dev = "baseline"`? Or do you only ever care about the baseline SD?

**Comment by jepusto** [comment]
Closed with https://github.com/jepusto/SingleCaseES/commit/dda9709080426348d039ea49aa62aa9db6f614e1
