### ISSUE TITLE
Plot tab doesn't work when Phase is coded 0 (baseline) / 1 (treatment)

### ISSUE THREAD

**Issue by pgrekov** [jepusto/SingleCaseES#78]
When using the plot tab within the multiple-series calculator for a dataset that codes phase as 0/1 instead of A/B I get an error saying "Error: Problem while computing 'treat_change = suppressWarnings(min(session)) - 0.5"

**Comment by pgrekov** [comment]
Just added [Bassette2013.xlsx](https://github.com/jepusto/SingleCaseES/blob/main/auxiliary/Bassette2013.xlsx)

Also, sorry put this in the wrong place!

**Comment by jepusto** [comment]
Fixed with https://github.com/jepusto/SingleCaseES/commit/f3b07ac4ca9560440c0ba8685ec9e9aad8535a3f
