### ISSUE TITLE
Fix warnings from dplyr 1.1.0

### ISSUE THREAD

**Issue by jepusto** [jepusto/SingleCaseES#91]
Unit tests are throwing deprecation warnings when run with dplyr version 1.1.0. Update functions to use non-deprecated functions/syntax.

**Comment by pgrekov** [comment]
done!

**Comment by jepusto** [comment]
Thanks! That was nice and simple.

**Comment by jepusto** [comment]
Closed with e834aa350e79ddbf3a6178e161bcbbf9428771e3
